baseurl="https://www.verso.re/"
googleAnalytics="UA-147436221-1"

languageCode="en-us"
DefaultContentLanguage="en"
paginate=6

theme="hello-friend"
enableEmoji=true
enableRobotsTXT=true
canonifyURLs=true

[params]
  author="Joan Calabr√©s"
  title = "verso.re"
  subtitle = "Reverse All The Things!"
  description="Welcome to verso.re :)"
  contentTypeName="posts"
  defaultTheme="dark"
  showMenuItems=6
  showReadingTime=false

[languages]
  [languages.en]
    keywords = "malware analysis, reverse engineering, mobile security, android, ghidra"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "01-02-2006"
    dateFormatList = "01-02-2006"
    [languages.en.params.logo]
      logoText = "./verso.re"
      logoHomeLink = "/"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
